#!/usr/bin/env python3
"""
Generate Sobol direction number table from Joe-Kuo initial direction numbers.

Reads noise/new-joe-kuo-6.21201 and produces
app/include/himalaya/app/sobol_direction_data.h with a constexpr uint32_t[4096]
array (128 dimensions × 32 bits, left-justified to 32 bits).

Reference: S. Joe and F. Y. Kuo, "Constructing Sobol sequences with better
two-dimensional projections", SIAM J. Sci. Comput. 30, 2635-2654 (2008).
"""

import pathlib
import sys

DIMS = 128
BITS = 32
REPO = pathlib.Path(__file__).resolve().parent.parent
INPUT = REPO / "noise" / "new-joe-kuo-6.21201"
OUTPUT = REPO / "app" / "include" / "himalaya" / "app" / "sobol_direction_data.h"


def generate_direction_numbers() -> list[int]:
    """Return DIMS*BITS left-justified 32-bit direction numbers."""
    table: list[int] = [0] * (DIMS * BITS)

    # Dimension 0: Van der Corput (base 2)
    for i in range(BITS):
        table[i] = 1 << (31 - i)

    # Dimensions 1..DIMS-1 from Joe-Kuo file (file rows start at d=2)
    with open(INPUT) as f:
        # Skip header line
        f.readline()
        dim_idx = 1
        for line in f:
            if dim_idx >= DIMS:
                break
            parts = line.split()
            if len(parts) < 3:
                continue
            # d, s, a, m_1 .. m_s
            s = int(parts[1])  # degree
            a = int(parts[2])  # polynomial coefficients
            m = [int(x) for x in parts[3:3 + s]]  # initial direction numbers

            v = [0] * BITS
            # Left-justify initial direction numbers
            for i in range(s):
                v[i] = m[i] << (31 - i)

            # Recurrence for remaining bits
            for i in range(s, BITS):
                v[i] = v[i - s] ^ (v[i - s] >> s)
                for k in range(1, s):
                    if (a >> (s - 1 - k)) & 1:
                        v[i] ^= v[i - k]

            base = dim_idx * BITS
            for i in range(BITS):
                table[base + i] = v[i]

            dim_idx += 1

    if dim_idx < DIMS:
        print(f"Warning: only {dim_idx} dimensions found, expected {DIMS}",
              file=sys.stderr)

    return table


def write_header(table: list[int]) -> None:
    """Write the C++ header file."""
    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("/**")
    lines.append(" * @file sobol_direction_data.h")
    lines.append(
        " * @brief 128-dimension 32-bit Sobol direction number table."
    )
    lines.append(" *")
    lines.append(
        " * Source: Joe & Kuo direction numbers (noise/new-joe-kuo-6.21201)."
    )
    lines.append(
        " * Generated by scripts/generate_sobol.py — do not edit manually."
    )
    lines.append(" */")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace himalaya::app {")
    lines.append("")
    lines.append(
        "/**"
    )
    lines.append(
        " * @brief 128-dimension Sobol direction numbers "
        "(left-justified 32-bit, 4096 entries)."
    )
    lines.append(" *")
    lines.append(
        " * Layout: kSobolDirectionData[dim * 32 + bit] where dim in [0,127], "
        "bit in [0,31]."
    )
    lines.append(
        " * Dimension 0 is Van der Corput (base 2). "
        "Dimensions 1-127 from Joe & Kuo."
    )
    lines.append(" */")
    lines.append("inline constexpr uint32_t kSobolDirectionData[4096] = {")

    # Write 8 values per line
    for i in range(0, len(table), 8):
        chunk = table[i:i + 8]
        hex_vals = ", ".join(f"0x{v:08X}" for v in chunk)
        comma = "," if i + 8 < len(table) else ""
        lines.append(f"    {hex_vals}{comma}")

    lines.append("};")
    lines.append("")
    lines.append("} // namespace himalaya::app")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {len(table)} entries to {OUTPUT}")


if __name__ == "__main__":
    data = generate_direction_numbers()
    write_header(data)
