#!/usr/bin/env python3
"""Generate Poisson Disk sample points inside the unit circle.

Uses dart-throwing with a fixed seed for reproducibility.
Outputs GLSL const vec2 arrays ready to paste into a shader.

Usage:
    python generate_poisson_disk.py
"""

import math
import random

SEED = 42
MIN_DIST_FACTOR = 0.7  # min_dist = factor / sqrt(N)


def generate_poisson_disk(n: int, seed: int) -> list[tuple[float, float]]:
    """Generate n points inside the unit circle via dart-throwing."""
    rng = random.Random(seed)
    min_dist = MIN_DIST_FACTOR / math.sqrt(n)
    points: list[tuple[float, float]] = []
    max_attempts = n * 1000

    for _ in range(max_attempts):
        if len(points) >= n:
            break
        # Uniform random point in unit circle
        angle = rng.uniform(0, 2 * math.pi)
        radius = math.sqrt(rng.uniform(0, 1))
        x = radius * math.cos(angle)
        y = radius * math.sin(angle)

        # Reject if too close to any existing point
        too_close = False
        for px, py in points:
            if (x - px) ** 2 + (y - py) ** 2 < min_dist ** 2:
                too_close = True
                break
        if not too_close:
            points.append((x, y))

    if len(points) < n:
        raise RuntimeError(f"Only generated {len(points)}/{n} points")
    return points


def format_glsl(name: str, points: list[tuple[float, float]]) -> str:
    """Format points as a GLSL const vec2 array."""
    lines = [f"const vec2 {name}[{len(points)}] = vec2[{len(points)}]("]
    for i, (x, y) in enumerate(points):
        comma = "," if i < len(points) - 1 else ""
        lines.append(f"    vec2({x: .6f}, {y: .6f}){comma}")
    lines.append(");")
    return "\n".join(lines)


def main() -> None:
    blocker_points = generate_poisson_disk(32, SEED)
    pcf_points = generate_poisson_disk(49, SEED + 1)

    print("// --- Poisson Disk samples (generated by scripts/generate_poisson_disk.py) ---")
    print(f"// Seed: {SEED}, min_dist_factor: {MIN_DIST_FACTOR}")
    print()
    print(format_glsl("kBlockerSearchSamples", blocker_points))
    print()
    print(format_glsl("kPCFSamples", pcf_points))


if __name__ == "__main__":
    main()
