/**
 * @file shadow.glsl
 * @brief CSM shadow sampling — cascade selection, PCF, PCSS, distance fade.
 *
 * Provides decomposed functions for the forward pass to assemble shadow
 * evaluation.  Intermediate results (cascade index, blend factor) remain
 * visible to callers for debug visualization.
 *
 * Depends on bindings.glsl being included first (GlobalUBO, rt_shadow_map,
 * rt_shadow_map_depth).
 */

#ifndef SHADOW_GLSL
#define SHADOW_GLSL

// ---- PCSS constants ----

#define PCSS_FLAG_BLOCKER_EARLY_OUT (1u << 0)

/** @brief Maximum receiver plane depth gradient (prevents grazing-angle light leak). */
const float kMaxReceiverPlaneGradient = 0.01;

/** @brief Maximum penumbra width in texels (caps kernel explosion from multi-layer occlusion). */
const float kMaxPenumbraTexels = 64.0;

// --- Poisson Disk samples (generated by scripts/generate_poisson_disk.py) ---
// Seed: 42, min_dist_factor: 0.7

const vec2 kBlockerSearchSamples[32] = vec2[32](
    vec2(-0.101245, -0.121491),
    vec2(-0.073994,  0.466622),
    vec2(-0.069841, -0.819647),
    vec2( 0.229741, -0.184818),
    vec2(-0.152260,  0.081327),
    vec2( 0.139177,  0.697126),
    vec2( 0.439729,  0.074003),
    vec2(-0.434337, -0.596902),
    vec2( 0.029408, -0.075060),
    vec2( 0.287075, -0.784683),
    vec2(-0.211805,  0.332593),
    vec2( 0.559328, -0.154099),
    vec2( 0.259666,  0.171143),
    vec2( 0.446755, -0.635717),
    vec2(-0.961020, -0.222613),
    vec2(-0.536913,  0.513581),
    vec2( 0.074465,  0.532769),
    vec2( 0.423107,  0.231886),
    vec2(-0.397489, -0.454791),
    vec2(-0.103045,  0.962308),
    vec2( 0.406000,  0.751193),
    vec2( 0.318875,  0.527043),
    vec2( 0.798267, -0.052623),
    vec2(-0.775006, -0.289792),
    vec2( 0.023518,  0.177615),
    vec2(-0.206850,  0.474293),
    vec2( 0.235674,  0.942002),
    vec2( 0.400054, -0.393237),
    vec2( 0.582072, -0.346474),
    vec2(-0.474948, -0.192784),
    vec2(-0.816835, -0.480211),
    vec2(-0.377837,  0.276695)
);

const vec2 kPCFSamples[49] = vec2[49](
    vec2( 0.810041,  0.200145),
    vec2( 0.420429,  0.534576),
    vec2(-0.420894, -0.784729),
    vec2(-0.675572,  0.204635),
    vec2( 0.652805,  0.078958),
    vec2(-0.641941,  0.663476),
    vec2(-0.831494, -0.252852),
    vec2(-0.384243,  0.168955),
    vec2( 0.536355, -0.729756),
    vec2(-0.219972,  0.217613),
    vec2(-0.702110, -0.054948),
    vec2( 0.107931, -0.765224),
    vec2( 0.899620,  0.364125),
    vec2( 0.288992, -0.461133),
    vec2( 0.553199, -0.464999),
    vec2( 0.737844,  0.557919),
    vec2(-0.833230, -0.488379),
    vec2(-0.131914, -0.276943),
    vec2(-0.636064, -0.618311),
    vec2( 0.463321, -0.341480),
    vec2(-0.823591, -0.151171),
    vec2( 0.459772,  0.798104),
    vec2( 0.043135, -0.219628),
    vec2(-0.509334, -0.329592),
    vec2( 0.304251,  0.715480),
    vec2( 0.729055, -0.142998),
    vec2( 0.532645,  0.459583),
    vec2( 0.177902, -0.961030),
    vec2( 0.308463,  0.178906),
    vec2( 0.698587,  0.420451),
    vec2(-0.182538,  0.068220),
    vec2( 0.950423,  0.015047),
    vec2( 0.348789, -0.051637),
    vec2(-0.096144, -0.989919),
    vec2( 0.774140, -0.534552),
    vec2(-0.443156,  0.721728),
    vec2(-0.968097,  0.011489),
    vec2(-0.267216, -0.878795),
    vec2( 0.387373, -0.485321),
    vec2( 0.263605,  0.931173),
    vec2(-0.683560,  0.466683),
    vec2(-0.453684, -0.233434),
    vec2(-0.275150,  0.520855),
    vec2( 0.165519,  0.387858),
    vec2( 0.392612, -0.743012),
    vec2( 0.455418, -0.120538),
    vec2( 0.106476,  0.668566),
    vec2( 0.152888,  0.061894),
    vec2( 0.598654,  0.637049)
);

// ---- PCSS utility functions ----

/**
 * Interleaved gradient noise for per-pixel Poisson Disk rotation.
 * Returns a value in [0, 1) that varies per screen pixel.
 * Jimenez 2014 (Call of Duty: Advanced Warfare).
 */
float interleaved_gradient_noise(vec2 screen_pos) {
    return fract(52.9829189 * fract(dot(screen_pos, vec2(0.06711056, 0.00583715))));
}

/**
 * Rotate a 2D sample by the given angle (radians).
 */
vec2 rotate_sample(vec2 s, float angle) {
    float c = cos(angle);
    float sn = sin(angle);
    return vec2(s.x * c - s.y * sn, s.x * sn + s.y * c);
}

// ---- ShadowProjData + prepare_shadow_proj ----

/**
 * Pre-computed shadow projection data for a single cascade.
 *
 * Encapsulates light-space UV, reference depth, and receiver plane
 * depth gradients.  Computed once in uniform control flow via
 * prepare_shadow_proj(), then consumed by blocker_search() and
 * sample_shadow_pcss() without further dFdx/dFdy calls.
 */
struct ShadowProjData {
    vec2  shadow_uv;   ///< Shadow map UV [0,1].
    float ref_depth;   ///< Light-space NDC depth (Reverse-Z).
    float dz_du;       ///< Depth gradient w.r.t. shadow U.
    float dz_dv;       ///< Depth gradient w.r.t. shadow V.
};

/**
 * Project a world-space point into shadow UV space and compute
 * receiver plane depth gradients via screen-space derivatives.
 *
 * MUST be called in uniform control flow — dFdx/dFdy require all
 * invocations in a quad to execute the same instruction.
 *
 * At cascade boundaries where the quad uses mixed cascade indices,
 * the gradients are zeroed (detected via dFdx/dFdy of cascade index)
 * to avoid cross-projection garbage.  Those pixels fall back to
 * normal offset + slope bias quality (1-2 pixel band, invisible).
 *
 * @param world_pos    Fragment world position.
 * @param world_normal Fragment world shading normal (normalized).
 * @param cascade      Cascade index.
 * @return Precomputed projection data for PCSS sampling.
 */
ShadowProjData prepare_shadow_proj(vec3 world_pos, vec3 world_normal, int cascade) {
    ShadowProjData proj;

    // Normal offset (same logic as sample_shadow / sample_shadow_pcf)
    float texel_ws = global.cascade_texel_world_size[cascade];
    vec3 offset_pos = world_pos + world_normal * global.shadow_normal_offset * texel_ws;

    // Project to light clip space (orthographic: w = 1)
    vec4 light_clip = global.cascade_view_proj[cascade] * vec4(offset_pos, 1.0);
    vec3 light_ndc = light_clip.xyz / light_clip.w;

    // NDC [-1,1] -> UV [0,1]
    proj.shadow_uv = light_ndc.xy * 0.5 + 0.5;
    proj.ref_depth = light_ndc.z;

    // Screen-space derivatives of shadow UV and depth
    vec2 duv_dx = dFdx(proj.shadow_uv);
    vec2 duv_dy = dFdy(proj.shadow_uv);
    float dz_dx = dFdx(proj.ref_depth);
    float dz_dy = dFdy(proj.ref_depth);

    // Solve 2x2 linear system for (dz_du, dz_dv):
    //   dz_dx = dz_du * duv_dx.x + dz_dv * duv_dx.y
    //   dz_dy = dz_du * duv_dy.x + dz_dv * duv_dy.y
    float det = duv_dx.x * duv_dy.y - duv_dx.y * duv_dy.x;
    float inv_det = (abs(det) > 1e-10) ? (1.0 / det) : 0.0;
    proj.dz_du = ( duv_dy.y * dz_dx - duv_dx.y * dz_dy) * inv_det;
    proj.dz_dv = (-duv_dy.x * dz_dx + duv_dx.x * dz_dy) * inv_det;

    // Clamp to prevent extreme gradients at grazing angles
    proj.dz_du = clamp(proj.dz_du, -kMaxReceiverPlaneGradient, kMaxReceiverPlaneGradient);
    proj.dz_dv = clamp(proj.dz_dv, -kMaxReceiverPlaneGradient, kMaxReceiverPlaneGradient);

    // Cascade boundary detection: zero gradients when the quad spans
    // different cascades (cross-projection derivatives are garbage)
    float cascade_uniform = step(abs(dFdx(float(cascade))) + abs(dFdy(float(cascade))), 0.0);
    proj.dz_du *= cascade_uniform;
    proj.dz_dv *= cascade_uniform;

    return proj;
}

/**
 * Search for blockers in the shadow map around the projected position.
 *
 * Samples raw depth values (via rt_shadow_map_depth, binding 6) in an
 * elliptical region scaled by cascade_light_size_uv (U) and
 * cascade_uv_scale_y (V).  Each sample applies per-pixel Poisson Disk
 * rotation and receiver plane depth bias.
 *
 * Reverse-Z blocker test: sampled_depth > adjusted_depth means the
 * texel is closer to the light (a blocker).
 *
 * @param proj          Precomputed projection data from prepare_shadow_proj().
 * @param cascade       Cascade index.
 * @param avg_blocker   Output: average blocker depth (NDC).
 * @param num_blockers  Output: number of blocker samples found.
 */
void blocker_search(ShadowProjData proj, int cascade,
                    out float avg_blocker, out float num_blockers) {
    avg_blocker = 0.0;
    num_blockers = 0.0;

    // Elliptical search radius: U from cascade_light_size_uv, V scaled by anisotropy
    float search_u = global.cascade_light_size_uv[cascade];
    float search_v = search_u * global.cascade_uv_scale_y[cascade];

    // Per-pixel rotation angle from interleaved gradient noise
    float rotation = interleaved_gradient_noise(gl_FragCoord.xy) * 6.2831853;

    float blocker_sum = 0.0;
    uint sample_count = global.pcss_blocker_samples;
    for (uint i = 0u; i < sample_count; ++i) {
        vec2 offset = rotate_sample(kBlockerSearchSamples[i], rotation)
                      * vec2(search_u, search_v);
        vec2 sample_uv = proj.shadow_uv + offset;

        // Receiver plane depth bias: adjust comparison depth per sample offset
        float adjusted_depth = proj.ref_depth + proj.dz_du * offset.x + proj.dz_dv * offset.y;

        // Read raw depth from shadow map (no comparison)
        float sampled_depth = texture(rt_shadow_map_depth, vec3(sample_uv, float(cascade))).r;

        // Reverse-Z: blocker is closer to light → larger depth value
        if (sampled_depth > adjusted_depth) {
            blocker_sum += sampled_depth;
            num_blockers += 1.0;
        }
    }

    if (num_blockers > 0.0) {
        avg_blocker = blocker_sum / num_blockers;
    }
}

/**
 * PCSS shadow sampling: blocker search → penumbra estimation → variable-width PCF.
 *
 * Produces contact-hardening shadows: hard at caster contact, softening with
 * distance.  Uses precomputed ShadowProjData (no dFdx/dFdy internally).
 *
 * Early-outs:
 *  - No blockers found → return 1.0 (fully lit).
 *  - All samples are blockers AND PCSS_FLAG_BLOCKER_EARLY_OUT set → return 0.0
 *    (mitigates multi-layer occlusion light leak).
 *
 * Penumbra estimation (directional light simplified formula):
 *  - penumbra_u = |blocker_ndc - receiver_ndc| * cascade_pcss_scale
 *  - penumbra_v = penumbra_u * cascade_uv_scale_y
 *  - Clamped to [shadow_texel_size, kMaxPenumbraTexels * shadow_texel_size]
 *
 * @param proj    Precomputed projection data from prepare_shadow_proj().
 * @param cascade Cascade index.
 * @return Shadow factor: 1.0 = fully lit, 0.0 = fully in shadow.
 */
float sample_shadow_pcss(ShadowProjData proj, int cascade) {
    // Step 1: Blocker search
    float avg_blocker, num_blockers;
    blocker_search(proj, cascade, avg_blocker, num_blockers);

    // No blockers → fully lit
    if (num_blockers < 1.0) {
        return 1.0;
    }

    // All blockers → early-out as fully shadowed (reduces multi-layer light leak)
    if (num_blockers >= float(global.pcss_blocker_samples)
        && (global.pcss_flags & PCSS_FLAG_BLOCKER_EARLY_OUT) != 0u) {
        return 0.0;
    }

    // Step 2: Penumbra estimation (directional light — no 1/dBlocker division)
    float delta_ndc = abs(avg_blocker - proj.ref_depth);
    float penumbra_u = delta_ndc * global.cascade_pcss_scale[cascade];
    float penumbra_v = penumbra_u * global.cascade_uv_scale_y[cascade];

    // Clamp: lower = 1 texel (prevents noise), upper = kMaxPenumbraTexels (prevents kernel explosion)
    float min_penumbra = global.shadow_texel_size;
    float max_penumbra = kMaxPenumbraTexels * global.shadow_texel_size;
    penumbra_u = clamp(penumbra_u, min_penumbra, max_penumbra);
    penumbra_v = clamp(penumbra_v, min_penumbra, max_penumbra);

    // Step 3: Variable-width PCF with elliptical Poisson Disk kernel
    float rotation = interleaved_gradient_noise(gl_FragCoord.xy) * 6.2831853;
    float shadow_sum = 0.0;
    uint sample_count = global.pcss_pcf_samples;
    for (uint i = 0u; i < sample_count; ++i) {
        vec2 offset = rotate_sample(kPCFSamples[i], rotation)
                      * vec2(penumbra_u, penumbra_v);
        vec2 sample_uv = proj.shadow_uv + offset;

        // Per-sample receiver plane depth bias
        float adjusted_depth = proj.ref_depth + proj.dz_du * offset.x + proj.dz_dv * offset.y;

        // Hardware comparison sampling (binding 5, GREATER_OR_EQUAL with Reverse-Z)
        shadow_sum += texture(rt_shadow_map, vec4(sample_uv, float(cascade), adjusted_depth));
    }

    return shadow_sum / float(sample_count);
}

/**
 * Select the cascade index for a given view-space depth.
 *
 * Compares view_depth against cascade_splits boundaries (PSSM-distributed).
 * Falls through to the last cascade if beyond all splits.
 *
 * When the fragment lies in the blend region near a cascade's far boundary,
 * blend_factor is non-zero (0..1) indicating how much to blend with the
 * next cascade.  For the last cascade, blend_factor is always 0 (distance
 * fade handles the far edge instead).
 *
 * @param view_depth   Positive linear distance from camera.
 * @param blend_factor Output: 0.0 = no blend, 1.0 = fully next cascade.
 * @return Cascade index [0, shadow_cascade_count).
 */
int select_cascade(float view_depth, out float blend_factor) {
    blend_factor = 0.0;

    int count = int(global.shadow_cascade_count);

    // cascade_splits holds far boundaries; pick the first cascade
    // whose far boundary exceeds the fragment's view-space depth.
    for (int i = 0; i < count - 1; ++i) {
        if (view_depth < global.cascade_splits[i]) {
            // Blend region: last (blend_width) fraction of this cascade's
            // split distance.  Smoothly ramps blend_factor from 0 to 1.
            float blend_start = global.cascade_splits[i]
                                * (1.0 - global.shadow_blend_width);
            if (view_depth > blend_start) {
                blend_factor = (view_depth - blend_start)
                               / (global.cascade_splits[i] - blend_start);
            }
            return i;
        }
    }
    return count - 1;
}

/**
 * Sample the shadow map with a single hardware comparison (hard shadow).
 *
 * Applies normal offset bias before projecting to light space: the sampling
 * position is pushed along the surface normal by an amount proportional to
 * the cascade's texel world size (precomputed on CPU, stored in GlobalUBO).
 * This complements the hardware depth bias (slope) set during shadow map
 * rendering.
 *
 * @param world_pos    Fragment world-space position.
 * @param world_normal Fragment world-space shading normal (normalized).
 * @param cascade      Cascade index.
 * @return Shadow factor: 1.0 = fully lit, 0.0 = fully in shadow.
 */
float sample_shadow(vec3 world_pos, vec3 world_normal, int cascade) {
    // Normal offset: push along normal to reduce acne on surfaces
    // nearly parallel to the light direction
    float texel_ws = global.cascade_texel_world_size[cascade];
    vec3 offset_pos = world_pos + world_normal * global.shadow_normal_offset * texel_ws;

    // Project to light clip space (w = 1 for orthographic, divide is a no-op)
    vec4 light_clip = global.cascade_view_proj[cascade] * vec4(offset_pos, 1.0);
    vec3 light_ndc = light_clip.xyz / light_clip.w;

    // NDC [-1,1] -> UV [0,1]
    vec2 shadow_uv = light_ndc.xy * 0.5 + 0.5;
    float ref_depth = light_ndc.z;

    // Hardware comparison: GREATER_OR_EQUAL with Reverse-Z
    // Returns 1.0 when ref_depth >= stored (lit), 0.0 when occluded
    return texture(rt_shadow_map, vec4(shadow_uv, float(cascade), ref_depth));
}

/**
 * Sample the shadow map with PCF (Percentage-Closer Filtering).
 *
 * Performs a (2R+1) x (2R+1) grid of hardware 2x2 comparison samples,
 * where R = shadow_pcf_radius from GlobalUBO.  Each texture() call on
 * sampler2DArrayShadow returns a bilinear-interpolated comparison over
 * a 2x2 texel footprint, so the effective filter is wider than the grid.
 *
 * When R = 0, falls back to a single hardware comparison (hard shadow),
 * identical to sample_shadow().
 *
 * @param world_pos    Fragment world-space position.
 * @param world_normal Fragment world-space shading normal (normalized).
 * @param cascade      Cascade index.
 * @return Shadow factor: 1.0 = fully lit, 0.0 = fully in shadow.
 */
float sample_shadow_pcf(vec3 world_pos, vec3 world_normal, int cascade) {
    // Normal offset (same logic as sample_shadow)
    float texel_ws = global.cascade_texel_world_size[cascade];
    vec3 offset_pos = world_pos + world_normal * global.shadow_normal_offset * texel_ws;

    // Project to light clip space (orthographic: w = 1)
    vec4 light_clip = global.cascade_view_proj[cascade] * vec4(offset_pos, 1.0);
    vec3 light_ndc = light_clip.xyz / light_clip.w;

    // NDC [-1,1] -> UV [0,1]
    vec2 shadow_uv = light_ndc.xy * 0.5 + 0.5;
    float ref_depth = light_ndc.z;

    int radius = int(global.shadow_pcf_radius);
    if (radius == 0) {
        return texture(rt_shadow_map, vec4(shadow_uv, float(cascade), ref_depth));
    }

    // (2R+1) x (2R+1) grid — each sample leverages hardware 2x2 comparison
    float sum = 0.0;
    float texel = global.shadow_texel_size;
    for (int y = -radius; y <= radius; ++y) {
        for (int x = -radius; x <= radius; ++x) {
            vec2 uv = shadow_uv + vec2(float(x), float(y)) * texel;
            sum += texture(rt_shadow_map, vec4(uv, float(cascade), ref_depth));
        }
    }

    return sum / float((2 * radius + 1) * (2 * radius + 1));
}

/**
 * Compute a fade factor near the maximum shadow distance.
 *
 * Returns 1.0 well within shadow range, smoothly fading to 0.0 as
 * view_depth approaches shadow_max_distance.  Apply as:
 *     shadow = mix(1.0, shadow, shadow_distance_fade(view_depth));
 *
 * Uses the independent shadow_distance_fade_width UBO field (not blend_width).
 *
 * @param view_depth Positive linear distance from camera.
 * @return Fade factor: 1.0 = keep shadow as-is, 0.0 = no shadow (fully lit).
 */
float shadow_distance_fade(float view_depth) {
    float fade_end = global.shadow_max_distance;
    float fade_start = fade_end * (1.0 - global.shadow_distance_fade_width);
    return 1.0 - smoothstep(fade_start, fade_end, view_depth);
}

/**
 * Evaluate shadow with cascade blending and distance fade.
 *
 * Single entry point for the forward pass: selects the cascade, samples
 * with PCF or PCSS based on shadow_mode, blends adjacent cascades in the
 * overlap region, and applies distance fade at the far edge.
 *
 * For PCSS mode, ShadowProjData for both current and next cascade is
 * precomputed BEFORE any non-uniform branching, ensuring dFdx/dFdy
 * execute in uniform control flow.  The extra ~25 ALU ops for the
 * second prepare_shadow_proj() is negligible vs 41 texture fetches.
 *
 * Blend strategy: linear interpolation (lerp) between the current and
 * next cascade.  The blend method is isolated here to facilitate a
 * future switch to dithering if needed.
 *
 * @param world_pos    Fragment world-space position.
 * @param world_normal Fragment world-space shading normal (normalized).
 * @param view_depth   Positive linear distance from camera.
 * @return Shadow factor: 1.0 = fully lit, 0.0 = fully in shadow.
 */
float blend_cascade_shadow(vec3 world_pos, vec3 world_normal, float view_depth) {
    float blend_factor;
    int cascade = select_cascade(view_depth, blend_factor);

    float shadow;

    if (global.shadow_mode == 1u) {
        // PCSS path: precompute ShadowProjData in uniform flow for both cascades
        int next_cascade = min(cascade + 1, int(global.shadow_cascade_count) - 1);
        ShadowProjData proj = prepare_shadow_proj(world_pos, world_normal, cascade);
        ShadowProjData next_proj = prepare_shadow_proj(world_pos, world_normal, next_cascade);

        shadow = sample_shadow_pcss(proj, cascade);

        // Blend with next cascade in the overlap region
        if (blend_factor > 0.0 && cascade < int(global.shadow_cascade_count) - 1) {
            float next_shadow = sample_shadow_pcss(next_proj, next_cascade);
            shadow = mix(shadow, next_shadow, blend_factor);
        }
    } else {
        // PCF path: existing behavior unchanged
        shadow = sample_shadow_pcf(world_pos, world_normal, cascade);

        if (blend_factor > 0.0 && cascade < int(global.shadow_cascade_count) - 1) {
            float next_shadow = sample_shadow_pcf(world_pos, world_normal, cascade + 1);
            shadow = mix(shadow, next_shadow, blend_factor);
        }
    }

    // Distance fade: last cascade far edge blends to fully lit
    shadow = mix(1.0, shadow, shadow_distance_fade(view_depth));

    return shadow;
}

#endif // SHADOW_GLSL
